import { Koulen, Bai_Jamjuree, Liu_Jian_Mao_Cao } from "next/font/google";
import "./globals.css";
import ThemeColorUpdater from "@/components/ThemeColorUpdater";

const koulen = Koulen({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-koulen",
  display: "swap",
});

const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-bai",
  display: "swap",
});
const liuJianMaoCao = Liu_Jian_Mao_Cao({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-liu",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${koulen.variable} ${baiJamjuree.variable}  ${liuJianMaoCao.variable}`}
      suppressHydrationWarning
    >
      <head>
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="antialiased">
        <ThemeColorUpdater />
        {children}
      </body>
    </html>
  );
}
